on:
  push:
    branches:
      - serverless
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-south-1"
      # sam build
      - run: sam build

      # Run Unit tests- Specify unit tests here

      # sam deploy
      - run: sam deploy --config-env default --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides "MONGOURI=$MONGOURI STAGE=Prod VERSION=14 ZOHOPASS=$ZOHOPASS"
        env:
          MONGOURI: ${{ secrets.MONGOURI }}
          ZOHOPASS: ${{ secrets.ZOHOPASS }}
